FROM node:12-alpine as build
WORKDIR /app
ENV PATH=/app/node_modules/.bin:$PATH
COPY . /app/
RUN npm install
RUN ng build --prod --outputPath=./dist/build

FROM nginx:1.19-alpine
COPY --from=build /app/dist/build /usr/share/nginx/html

